# Generated by Django 3.1.4 on 2020-12-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20201209_0528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_name',
            new_name='USER',
        ),
    ]
